from __future__ import annotations

from enum import Enum


GRID_ROWS = 5
GRID_COLS = 9
INITIAL_SUN = 150
SUN_VALUE = 25
SKY_SUN_FALL_SPEED = 80
SUN_LIFETIME = 8.0
SUN_CLICK_RADIUS = 28
SUNFLOWER_INTERVAL = 7.0
PEASHOOTER_COOLDOWN = 1.5
PEA_SPEED = 3.0
PEA_DAMAGE = 20
ZOMBIE_HEALTH = 100
ZOMBIE_SPEED = 0.25
ZOMBIE_EAT_DISTANCE = 0.4
ZOMBIE_DAMAGE_PER_SECOND = 25
HIT_DISTANCE = 0.25
GAME_OVER_X = 0


class PlantType(str, Enum):
    SUNFLOWER = "sunflower"
    PEASHOOTER = "peashooter"


PLANT_COSTS: dict[PlantType, int] = {
    PlantType.SUNFLOWER: 50,
    PlantType.PEASHOOTER: 100,
}
